---
- name: DB Start database
  service: name=postgresql state=started enabled=yes

- name: DB create user
  postgresql_user: 
   name: apps
   password: "apps"
   state: present
   role_attr_flags: CREATEDB
  become_user: postgres
  become: yes


- name: DB Create database
  postgresql_db:
    name: db_apps
    owner: apps
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become_user: postgres
  become: yes

- name: DB grant priv
  postgresql_privs:
   db: db_apps
   privs: ALL
   type: database
   role: apps
  become_user: postgres
  become: yes


