---
- name: DB Start database
  service: name=postgresql state=started enabled=yes

- name: DB create user
  postgresql_user: 
   name: "{{app_db_user}}"
   password: "{{app_db_password}}"
   state: present
   role_attr_flags: CREATEDB
  become_user: postgres
  become: yes


- name: DB Create database
  postgresql_db:
    name: "{{app_db_name}}"
    owner: "{{app_db_user}}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become_user: postgres
  become: yes

- name: DB grant priv
  postgresql_privs:
   db: "{{app_db_name}}"
   privs: ALL
   type: database
   role: "{{app_db_user}}"
  become_user: postgres
  become: yes


