---
# tasks file for setup-os
- hostname:
    name: devtest

- name: Add passanger
  copy:
   dest: '/etc/apt/sources.list.d/passenger.list'
   content: "deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main"
   
- name: Add an Apt signing key, will not download if present
  apt_key:
   id: 561F9B9CAC40B2F7
   keyserver: hkp://keyserver.ubuntu.com:80
   state: present

- name: OS Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ruby-rails
    - dirmngr 
    - gnupg
    - apt-transport-https 
    - ca-certificates
    - nginx
    - libnginx-mod-http-passenger
    - postgresql-common
    - postgresql
    - libpq-dev
    - ruby-pg
    - python-psycopg2  

- name: OS Create new dir
  file:
    path: /u01
    state: directory
    mode: 0755

- name: OS Add user
  user: 
   name: apps
   home: /u01/apps
   ssh_key_bits: 2048
   generate_ssh_key: true
   shell: /bin/bash

- name: OS Remove nginx default page
  file:
   path: /etc/nginx/sites-enabled/default
   state: absent

- name: OS Add nginx app page
  template:
   src: ../templates/hello.j2
   dest: /etc/nginx/sites-available/hello.conf
   owner: root
   group: root
   mode: '0644'

- name: OS Link nginx app page
  file:
   src: /etc/nginx/sites-available/hello.conf
   dest: /etc/nginx/sites-enabled/hello.conf
   owner: root
   group: root
   state: link

