---
- name: Prepare Host for env
  hosts: all

  roles:
          - role: setup-os
            tags: ['os']

          - role: setup-rails
            tags: ['rails']

          - role: setup-apps
            become_user: "{{VMUSER}}"
            become: yes
            ignore_errors: true
            tags: ['apps']

          - role: setup-prod
            when: inventory_hostname == "prod"
            tags: ['prod']

            
